//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RussianEntities : DbContext
    {
        public RussianEntities()
            : base("name=RussianEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<aspnet_Users> aspnet_Users { get; set; }
        public virtual DbSet<tClassNumber> tClassNumber { get; set; }
        public virtual DbSet<tQuestion> tQuestion { get; set; }
        public virtual DbSet<tQuestionType> tQuestionType { get; set; }
        public virtual DbSet<tTheme> tTheme { get; set; }
        public virtual DbSet<aspnet_Roles> aspnet_Roles { get; set; }
        public virtual DbSet<tUserInfo> tUserInfo { get; set; }
    }
}
