//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tAnswer
    {
        public System.Guid pk { get; set; }
        public string textOfAnswer { get; set; }
        public System.Guid fkQuestion { get; set; }
        public System.Guid fkCurrentQuestion { get; set; }
        public bool deleted { get; set; }
    
        public virtual tQuestion tQuestion { get; set; }
        public virtual tQuestion tQuestion1 { get; set; }
    }
}
