//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tQuestion
    {
        public System.Guid pk { get; set; }
        public string questionText { get; set; }
        public System.Guid fkType { get; set; }
        public System.Guid fkClassNumber { get; set; }
        public bool deleted { get; set; }
        public System.Guid fkTheme { get; set; }
    
        public virtual tClassNumber tClassNumber { get; set; }
        public virtual tQuestionType tQuestionType { get; set; }
        public virtual tTheme tTheme { get; set; }
    }
}
