//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tQuestion
    {
        public tQuestion()
        {
            this.tAnswer = new HashSet<tAnswer>();
            this.tAnswer1 = new HashSet<tAnswer>();
        }
    
        public System.Guid pk { get; set; }
        public string questionText { get; set; }
        public System.Guid fkType { get; set; }
        public System.Guid fkClassNumber { get; set; }
        public bool deleted { get; set; }
    
        public virtual ICollection<tAnswer> tAnswer { get; set; }
        public virtual ICollection<tAnswer> tAnswer1 { get; set; }
        public virtual tClassNumber tClassNumber { get; set; }
        public virtual tQuestionType tQuestionType { get; set; }
    }
}
