//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tUserInfo
    {
        public System.Guid pk { get; set; }
        public System.Guid fkUser { get; set; }
        public int money { get; set; }
        public string info { get; set; }
        public bool deleted { get; set; }
    
        public virtual aspnet_Users aspnet_Users { get; set; }
    }
}
